---
- name: Check if "Swarm Mode" is enabled.
  shell: docker info
  changed_when: False
  register: docker_info
  tags: swarm

- name: Init "Swarm Mode" on the first manager.
  shell: docker swarm init
        --listen-addr {{ docker_swarm_addr }}:{{ docker_swarm_port }}
        --advertise-addr {{ docker_swarm_addr }} &&
        docker swarm update --task-history-limit={{ docker_swarm_task_history_limit }}
  when: "docker_info.stdout.find('Swarm: active') == -1
    and inventory_hostname == groups['node_role_manager'][0]"
  tags: swarm

- name: Get the worker join-token.
  shell: docker swarm join-token -q worker
  changed_when: False
  register: docker_worker_token
  delegate_to: "{{ groups['node_role_manager'][0] }}"
  delegate_facts: True
  when: "'node_role_worker' in group_names"
  tags: swarm

- name: Get the manager join-token.
  shell: docker swarm join-token -q manager
  changed_when: False
  register: docker_manager_token
  delegate_to: "{{ groups['node_role_manager'][0] }}"
  delegate_facts: True
  when: "'node_role_manager' in group_names
    and inventory_hostname != groups['node_role_manager'][0]"
  tags: swarm

- name: Declare the address of the first Swarm manager as a fact.
  set_fact:
    docker_manager_address: "{{ docker_swarm_addr }}:{{ docker_swarm_port }}"
  when: "inventory_hostname == groups['node_role_manager'][0]"
  tags: swarm

- name: Distribute the fact containing address of the first Swarm manager.
  set_fact:
    docker_manager_address: "{{hostvars[groups['node_role_manager'][0]]['docker_manager_address'] }}"
  when: "inventory_hostname != groups['node_role_manager'][0]"
  tags: swarm

- name: Join the pending Swarm worker nodes.
  shell: docker swarm join
        --listen-addr {{ docker_swarm_addr }}:{{ docker_swarm_port }}
        --advertise-addr {{ docker_swarm_addr }}
        --token "{{ docker_worker_token.stdout }}"
        {{ docker_manager_address }}
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1
    and docker_info.stdout.find('Swarm: pending') == -1
    and 'node_role_worker' in group_names"
  tags: swarm

- name: Join the pending Swarm manager nodes.
  shell: docker swarm join
        --listen-addr {{ docker_swarm_addr }}:{{ docker_swarm_port }}
        --advertise-addr {{ docker_swarm_addr }}
        --token "{{ docker_manager_token.stdout }}"
        {{ docker_manager_address }}
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1
    and docker_info.stdout.find('Swarm: pending') == -1
    and 'node_role_manager' in group_names
    and inventory_hostname != groups['node_role_manager'][0]"
  tags: swarm

#- name: Install weave plugin.
#  shell: docker plugin ls | grep weaveworks || docker plugin install weaveworks/net-plugin:latest_release --grant-all-permissions
#  changed_when: False
#  when: "'node_roles' in group_names"
#  tags: swarm
